# Generated by Django 5.2.1 on 2025-05-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('in_progress', 'İşlemde'), ('resolved', 'Tamamlandı')], default='pending', max_length=20),
        ),
    ]
