# Generated by Django 5.2.1 on 2025-06-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicerequest_address_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
